Switch to awk

diff --git a/.github/workflows/reddit.yml b/.github/workflows/reddit.yml
--- a/.github/workflows/reddit.yml
+++ b/.github/workflows/reddit.yml
@@ -42,7 +42,7 @@ jobs:
             if [ ! -s icon.png ]; then 
                 echo "icon not found or 0 size, downloading.."
                 set -x
-                curl -l -A "${{ secrets.REDDIT_USER_AGENT }}" $(jq -r '.icon' about.json | sed 's/\(.*\)\?.*/\1/g') > icon.png || echo "icon.png download FAILED"
+                curl -l -A "${{ secrets.REDDIT_USER_AGENT }}" $(jq -r '.icon' about.json | awk -F? '{print $1}' ) > icon.png || echo "icon.png download FAILED"
                 set +x
             fi
             git add -A
