Download icon each time

diff --git a/.github/workflows/reddit.yml b/.github/workflows/reddit.yml
--- a/.github/workflows/reddit.yml
+++ b/.github/workflows/reddit.yml
@@ -39,12 +39,8 @@ jobs:
             git config user.email "actions@users.noreply.github.com"
             cp ../${LINE}-about.json about.json
             cp ../${LINE}-subreddit.json subreddit.json
-            if [ ! -s icon.png ]; then 
-                echo "icon not found or 0 size, downloading.."
-                set -x
-                curl -l -A "${{ secrets.REDDIT_USER_AGENT }}" $(jq -r '.icon' about.json | awk -F? '{print $1}' ) > icon.png || echo "icon.png download FAILED"
-                set +x
-            fi
+            ICON_FILE=$(jq -r '.icon' about.json | awk -F? '{print $1}')
+            curl -l -A "${{ secrets.REDDIT_USER_AGENT }}" ${ICON_FILE} > ${ICON_FILE##*/} || echo "icon.png download FAILED"
             git add -A
             timestamp=$(date -u)
             git commit -m "Latest data: ${timestamp}" || exit 0
